[package]
name = "viewer-egui"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
eframe = { version = "0.36.2", default-features = false, features = ["wgpu", "default_fonts", "wayland", "x11"] }
egui-wgpu = "0.36.2"
glam = "0.34.0"
stepv = { version = "0.0.0", path = "../..", default-features = false }

[workspace]
